<?php

namespace AppBundle\Repository\Business;

/**
 * PrixRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrixRepository extends \Doctrine\ORM\EntityRepository
{
}
