<?php

namespace AppBundle\Repository\Business;

/**
 * ProduitAcheteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitAcheteRepository extends \Doctrine\ORM\EntityRepository
{
}
