<?php

namespace AppBundle\Repository\Business;

/**
 * ProduitStockeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitStockeRepository extends \Doctrine\ORM\EntityRepository
{
}
